baseURL = 'https://rishabhsamb.github.io/'
languageCode = 'en-us'
title = 'Rishabh Sambare'
theme = "morphism"

contentdir = "content"
layoutdir = "layouts"
publishdir = "docs"

[author]
    name = "Rishabh Sambare"

[taxonomies]
    category = "categories"
    group = "groups"
    series = "series"
    tag = "tags"

[permalinks]
    post = "/:section/:year/:month/:filename/"

[params]
    subtitle = "sick of tea? that's like being sick of breathing."
    showFooter = false
    showPoweredBy = false
    googleAnalyticsID = "G-3VQHNGCWXX"
    # listPaginatorLimit = 1000000

[[menu.footer]]
  name = "GitHub"
  pre = ""
  weight = -100
  identifier = "github"
  url = "https://github.com/rishabhsamb"
[[menu.footer]]
  name = "Resume"
  pre = ""
  weight = -90
  identifier = "resume"
  url = "./files/rishabhsambareresume.pdf"
[[menu.footer]]
  name = "LinkedIn"
  pre = ""
  weight = -80
  identifier = "linkedin"
  url = "https://www.linkedin.com/in/rishabhsamb"
